### ISSUE TITLE
Cursor should be pointer for Clickable Items

### ISSUE THREAD

**Issue by snegicodes** [Shruti-2303/YouTube-Project#1]
The cursor should be pointer for clickable items, such as:
1. Navbar Buttons
2. SideBar Button and Texts
3. Search Suggestions

**Comment by Shruti-2303** [comment]
Issue resolved in [this commit](https://github.com/Shruti-2303/YouTube-Project/commit/92eeae3c08ee21073cfc3f95e93f2af6360bf2ea)
